version: "3.0"
services:
  elasticsearch:
    image: elasticsearch:7.11.1
    container_name: elasticsearch 
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    restart: always 
    volumes:
      - elasticsearch/:/usr/share/elasticsearch/
  kibana:
    image: kibana:7.11.1 
    container_name: kibana
    hostname: kibana
    ports: 
      - "5601:5601"
    environment:
      LASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch 
    links:
      - elasticsearch:elasticsearch
    volumes:
      - kibana/:/usr/share/kibana/
    restart: always  
volumes:
  elasticsearch: 
    external:
      true
  kibana:
    external:
      true
